input {
  kafka {
    bootstrap_servers => "${KAFKA_BOOTSTRAP}"
    topics            => ["pa5220.raw", "pa5220.enriched", "pa5220.features"]
    group_id          => "logstash-soc"
    codec             => json
    auto_offset_reset => "earliest"
  }
}

filter {
  mutate {
    add_field => { "[@metadata][index]" => "soc-%{[kafka][topic]}" }
  }
  date {
    match  => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["${ES_HOST}"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}
